#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>
#include <string.h>
#include <pthread.h>
#include <sys/types.h>
#include <time.h>
#include <error.h>
#include <assert.h>
#include <wchar.h>
#include <signal.h>
#include <pwd.h>
#include <getopt.h>
#include <setjmp.h>
#include <ctype.h>
#include <syslog.h>
#include <ncurses.h>
#include <locale.h>
